### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by hhbusui** [kaindev8/starMQ#7]
## 环境
PHP7.4
MySQL 5.7
Nginx 1.22.1

## 问题
Warning: require(/www/wwwroot/xx.cn/vendor/composer/../symfony/deprecation-contracts/function.php): failed to open stream: No such file or directory in /www/wwwroot/xx.cn/vendor/composer/autoload_real.php on line 55

Fatal error: require(): Failed opening required '/www/wwwroot/xx.cn/vendor/composer/../symfony/deprecation-contracts/function.php' (include_path='.:') in /www/wwwroot/xx.cn/vendor/composer/autoload_real.php on line 55

**Comment by kaindev8** [comment]
使用群文件的压缩包
